### ISSUE TITLE
Help / Explanation

### ISSUE THREAD

**Issue by mitghi** [sharow/experiments#1]
@sharow What kind of magic is this? It is awesome. Would you please explain how it works? I would like to implement it for aarch64. I also found this: https://gist.github.com/lpereira/5062388

I understand the following from the code added to `mmap` region:

1. Each time `partial(...)` gets called from scratch ( on original function ), callee registers are moved one to the right, replacing `x0` with the first argument )
2. Each time `partial(...)` on previously curried function gets called, the same procedure applies but when a previously curried function gets called, it moves the registers one to the right again, effectively building correct order of arguments from x0 to x8. where most inner call has the x0 and most outer call has the rest of arguments.

Is my understanding of the code correct?

```
stp x8, x8, [sp, #-16]!
mov x8, x7
mov x7, x6
mov x6, x5
mov x5, x4
mov x4, x3
mov x3, x2
mov x2, x1
mov x1, x0
ldr x0, FIRST_ARGUMENT
ldr x19, FUNCTION_PTR
blr x19
ldp x8, x8, [sp], #16
```

Thanks.

**Comment by sharow** [comment]
> I understand the following from the code added to mmap region:

Yes. correct.
except, it not `curried `. currying is more higher order function mumbo ... thing. not partial function.

> ... but not the same as, partial application. 
https://en.wikipedia.org/wiki/Currying


btw, current implementation has crucial limitation. can you spot it?

<details>
<summary>limitation</summary>

```c
#include <stdio.h>
#include <partial/partial.h>

void greet(char *who, int a, int b, int c, int d, int e, int f, int g)
{
    printf("hello %s!\n", who);
    printf("%d %d %d %d %d %d %d\n", a, b, c, d, e, f, g);
}

int main(void)
{
    greet("A", 1, 2, 3, 4, 5, 6, 7);
    void (*greet_to_A)(int a, int b, int c, int d, int e, int f, int g) = partial(greet, "A");
    greet_to_A(1, 2, 3, 4, 5, 6, 7);

    unpartial(greet_to_A);
}
```

```
$ gcc -Iinclude main.c src/partial.c
$ ./a.out
hello A!
1 2 3 4 5 6 7
hello A!
1 2 3 4 5 6 -1565580721
```

in x86_64(+linux), 8th or higher arguments is passed by stack. it's overwritten by `push r9`, and rsp is shifted.
those limitation makes this more impractical.

</details>

----

> https://gist.github.com/lpereira/5062388

interesting.. but! This doesn't work with my i686-pc.
I did few digging with gdb, turns out it's depend on `partial_template_function()`'s code(object).
which mean, it's depend on compiler option.
for simple `gcc`(-O0), "segmentation fault (core dumped)".
gcc with `-O1`, `-O2`, it's works.


either way, there is no best solution tho..

**Comment by mitghi** [comment]
@sharow Thanks for the explanation. That's right, my mistake. This is pretty interesting though, because it makes something similar to method call possible which is included in examples that you provided. I find this very interesting. I can imagine in some scenarios that might come handy, for example passing the method as delegate ( similar to Objective-C ).

I couldn't get the code from that gist to work too.
I also found this one: https://github.com/dlenski/c-curry/blob/main/curry.c
